services:
  db_service:
    platform: linux/amd64
    image: postgres:13
    ports:
      - "5432:5432"
    env_file:
      - .env.db
    volumes:
      - postgresql_data:/var/lib/postgresql/data/

  redis:
    platform: linux/amd64
    image: redis:alpine

  frontend:
    platform: linux/amd64
    image: silvinwillemsen/choras-frontend:latest
    ports:
      - "5173:5173"
    environment:
      - REACT_APP_API_URL=http://localhost:5001
    depends_on:
      - backend

  backend:
    platform: linux/amd64
    image: silvinwillemsen/choras-backend:latest
    ports:
      - "5001:5001"
    env_file:
      - .env.api
    depends_on:
      - db_service
      - redis



volumes:
  postgresql_data:
